name: Update Formula on Release

on:
  repository_dispatch:
    types: [update-formula]

jobs:
  update-formula:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout homebrew-koh repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update formula
        run: |
          TAG_NAME="${{ github.event.client_payload.tag }}"
          COMMIT_SHA="${{ github.event.client_payload.sha }}"

          echo "Updating formula with:"
          echo "  Tag: $TAG_NAME"
          echo "  SHA: $COMMIT_SHA"

          # Update the formula file
          sed -i "s/tag:.*\".*\"/tag:      \"$TAG_NAME\"/" Formula/koh.rb
          sed -i "s/revision:.*\".*\"/revision: \"$COMMIT_SHA\"/" Formula/koh.rb

          echo "Formula updated successfully"

      - name: Verify formula syntax
        run: |
          ruby -c Formula/koh.rb
          echo "Formula syntax is valid"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add Formula/koh.rb

          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update formula to ${{ github.event.client_payload.tag }}"
            git push origin main
            echo "Formula updated and pushed"
          fi
